// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egfypndorwpjgbijsgrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZnlwbmRvcndwamdiaWpzZ3JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjEyMjUsImV4cCI6MjA2NDMzNzIyNX0.752ZxhKkAW1qAlmRk80sEoTh5kHm39SR3eMvVqGXcNQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);